image: gitpod/workspace-full

env:
  DB_DRIVER: sqlite

tasks:
  - init: php init_sqlite.php
    command: php -S 0.0.0.0:8080 -t .

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - bmewburn.vscode-intelephense-client
    - esbenp.prettier-vscode
